-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_blck_compute_depthwise_Pipeline_VITIS_LOOP_199_1_VITIS_LOOP_200_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_WREADY : IN STD_LOGIC;
    m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RVALID : IN STD_LOGIC;
    m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_RLAST : IN STD_LOGIC;
    m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BVALID : IN STD_LOGIC;
    m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    bound : IN STD_LOGIC_VECTOR (3 downto 0);
    local_weights_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_weights_ce0 : OUT STD_LOGIC;
    local_weights_we0 : OUT STD_LOGIC;
    local_weights_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    zext_ln193_1 : IN STD_LOGIC_VECTOR (5 downto 0);
    local_weights_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_weights_1_ce0 : OUT STD_LOGIC;
    local_weights_1_we0 : OUT STD_LOGIC;
    local_weights_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_weights_2_ce0 : OUT STD_LOGIC;
    local_weights_2_we0 : OUT STD_LOGIC;
    local_weights_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_weights_3_ce0 : OUT STD_LOGIC;
    local_weights_3_we0 : OUT STD_LOGIC;
    local_weights_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_weights_4_ce0 : OUT STD_LOGIC;
    local_weights_4_we0 : OUT STD_LOGIC;
    local_weights_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_weights_5_ce0 : OUT STD_LOGIC;
    local_weights_5_we0 : OUT STD_LOGIC;
    local_weights_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_weights_6_ce0 : OUT STD_LOGIC;
    local_weights_6_we0 : OUT STD_LOGIC;
    local_weights_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_weights_7_ce0 : OUT STD_LOGIC;
    local_weights_7_we0 : OUT STD_LOGIC;
    local_weights_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_weights_8_ce0 : OUT STD_LOGIC;
    local_weights_8_we0 : OUT STD_LOGIC;
    local_weights_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kernel_h : IN STD_LOGIC_VECTOR (1 downto 0);
    zext_ln193 : IN STD_LOGIC_VECTOR (1 downto 0);
    empty : IN STD_LOGIC_VECTOR (6 downto 0);
    filter_data : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of conv2d_blck_compute_depthwise_Pipeline_VITIS_LOOP_199_1_VITIS_LOOP_200_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln199_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem1_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal p_cast_fu_285_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_cast_reg_505 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln193_cast_fu_289_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln193_cast_reg_510 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln193_1_cast_fu_293_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln193_1_cast_reg_515 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln202_fu_378_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter11_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln202_reg_533_pp0_iter12_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln202_fu_403_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln202_reg_538 : STD_LOGIC_VECTOR (9 downto 0);
    signal gmem1_addr_reg_543 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln203_fu_441_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln203_reg_549 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln203_reg_549_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln203_reg_549_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln203_reg_549_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln203_reg_549_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln203_reg_549_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln203_reg_549_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln203_reg_549_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln203_reg_549_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln203_reg_549_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem1_addr_read_reg_554 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal sext_ln203_fu_431_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal kw_fu_108 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln200_fu_384_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal kh_fu_112 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln199_1_fu_357_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten_fu_116 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln199_1_fu_321_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal local_weights_7_we0_local : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal trunc_ln203_1_fu_461_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal local_weights_7_ce0_local : STD_LOGIC;
    signal local_weights_6_we0_local : STD_LOGIC;
    signal local_weights_6_ce0_local : STD_LOGIC;
    signal local_weights_5_we0_local : STD_LOGIC;
    signal local_weights_5_ce0_local : STD_LOGIC;
    signal local_weights_4_we0_local : STD_LOGIC;
    signal local_weights_4_ce0_local : STD_LOGIC;
    signal local_weights_3_we0_local : STD_LOGIC;
    signal local_weights_3_ce0_local : STD_LOGIC;
    signal local_weights_2_we0_local : STD_LOGIC;
    signal local_weights_2_ce0_local : STD_LOGIC;
    signal local_weights_1_we0_local : STD_LOGIC;
    signal local_weights_1_ce0_local : STD_LOGIC;
    signal local_weights_we0_local : STD_LOGIC;
    signal local_weights_ce0_local : STD_LOGIC;
    signal local_weights_8_we0_local : STD_LOGIC;
    signal local_weights_8_ce0_local : STD_LOGIC;
    signal icmp_ln200_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln199_fu_338_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_75_fu_369_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_75_fu_369_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln199_fu_349_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln200_fu_374_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_75_fu_369_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln202_fu_403_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln202_fu_403_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln203_fu_408_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln203_1_fu_411_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln203_fu_416_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln203_2_fu_421_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal shl_ln_fu_445_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln203_1_fu_452_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln203_fu_456_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal empty_75_fu_369_p00 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln202_fu_403_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_blck_mul_2ns_2ns_4_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (1 downto 0);
        din1 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component conv2d_blck_mul_4ns_7ns_10_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component conv2d_blck_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_2ns_2ns_4_1_1_U1 : component conv2d_blck_mul_2ns_2ns_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 2,
        din1_WIDTH => 2,
        dout_WIDTH => 4)
    port map (
        din0 => empty_75_fu_369_p0,
        din1 => empty_75_fu_369_p1,
        dout => empty_75_fu_369_p2);

    mul_4ns_7ns_10_1_1_U2 : component conv2d_blck_mul_4ns_7ns_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 7,
        dout_WIDTH => 10)
    port map (
        din0 => mul_ln202_fu_403_p0,
        din1 => mul_ln202_fu_403_p1,
        dout => mul_ln202_fu_403_p2);

    flow_control_loop_pipe_sequential_init_U : component conv2d_blck_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln199_fu_315_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_116 <= add_ln199_1_fu_321_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_116 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    kh_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    kh_fu_112 <= ap_const_lv2_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    kh_fu_112 <= select_ln199_1_fu_357_p3;
                end if;
            end if; 
        end if;
    end process;

    kw_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    kw_fu_108 <= ap_const_lv2_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    kw_fu_108 <= add_ln200_fu_384_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                add_ln202_reg_533 <= add_ln202_fu_378_p2;
                    p_cast_reg_505(6 downto 0) <= p_cast_fu_285_p1(6 downto 0);
                    zext_ln193_1_cast_reg_515(5 downto 0) <= zext_ln193_1_cast_fu_293_p1(5 downto 0);
                    zext_ln193_cast_reg_510(1 downto 0) <= zext_ln193_cast_fu_289_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln202_reg_533_pp0_iter10_reg <= add_ln202_reg_533_pp0_iter9_reg;
                add_ln202_reg_533_pp0_iter11_reg <= add_ln202_reg_533_pp0_iter10_reg;
                add_ln202_reg_533_pp0_iter12_reg <= add_ln202_reg_533_pp0_iter11_reg;
                add_ln202_reg_533_pp0_iter2_reg <= add_ln202_reg_533;
                add_ln202_reg_533_pp0_iter3_reg <= add_ln202_reg_533_pp0_iter2_reg;
                add_ln202_reg_533_pp0_iter4_reg <= add_ln202_reg_533_pp0_iter3_reg;
                add_ln202_reg_533_pp0_iter5_reg <= add_ln202_reg_533_pp0_iter4_reg;
                add_ln202_reg_533_pp0_iter6_reg <= add_ln202_reg_533_pp0_iter5_reg;
                add_ln202_reg_533_pp0_iter7_reg <= add_ln202_reg_533_pp0_iter6_reg;
                add_ln202_reg_533_pp0_iter8_reg <= add_ln202_reg_533_pp0_iter7_reg;
                add_ln202_reg_533_pp0_iter9_reg <= add_ln202_reg_533_pp0_iter8_reg;
                gmem1_addr_read_reg_554 <= m_axi_gmem1_0_RDATA;
                gmem1_addr_reg_543 <= sext_ln203_fu_431_p1;
                mul_ln202_reg_538 <= mul_ln202_fu_403_p2;
                trunc_ln203_reg_549 <= trunc_ln203_fu_441_p1;
                trunc_ln203_reg_549_pp0_iter10_reg <= trunc_ln203_reg_549_pp0_iter9_reg;
                trunc_ln203_reg_549_pp0_iter11_reg <= trunc_ln203_reg_549_pp0_iter10_reg;
                trunc_ln203_reg_549_pp0_iter12_reg <= trunc_ln203_reg_549_pp0_iter11_reg;
                trunc_ln203_reg_549_pp0_iter4_reg <= trunc_ln203_reg_549;
                trunc_ln203_reg_549_pp0_iter5_reg <= trunc_ln203_reg_549_pp0_iter4_reg;
                trunc_ln203_reg_549_pp0_iter6_reg <= trunc_ln203_reg_549_pp0_iter5_reg;
                trunc_ln203_reg_549_pp0_iter7_reg <= trunc_ln203_reg_549_pp0_iter6_reg;
                trunc_ln203_reg_549_pp0_iter8_reg <= trunc_ln203_reg_549_pp0_iter7_reg;
                trunc_ln203_reg_549_pp0_iter9_reg <= trunc_ln203_reg_549_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    p_cast_reg_505(9 downto 7) <= "000";
    zext_ln193_cast_reg_510(3 downto 2) <= "00";
    zext_ln193_1_cast_reg_515(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln199_1_fu_321_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv4_1));
    add_ln199_fu_338_p2 <= std_logic_vector(unsigned(kh_fu_112) + unsigned(ap_const_lv2_1));
    add_ln200_fu_384_p2 <= std_logic_vector(unsigned(select_ln199_fu_349_p3) + unsigned(ap_const_lv2_1));
    add_ln202_fu_378_p2 <= std_logic_vector(unsigned(zext_ln200_fu_374_p1) + unsigned(empty_75_fu_369_p2));
    add_ln203_1_fu_411_p2 <= std_logic_vector(unsigned(zext_ln203_fu_408_p1) + unsigned(filter_data));
    add_ln203_fu_416_p2 <= std_logic_vector(unsigned(add_ln203_1_fu_411_p2) + unsigned(zext_ln193_1_cast_reg_515));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter12, m_axi_gmem1_0_ARREADY, m_axi_gmem1_0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (m_axi_gmem1_0_RVALID = ap_const_logic_0)) or ((m_axi_gmem1_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter12, m_axi_gmem1_0_ARREADY, m_axi_gmem1_0_RVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (m_axi_gmem1_0_RVALID = ap_const_logic_0)) or ((m_axi_gmem1_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter12, m_axi_gmem1_0_ARREADY, m_axi_gmem1_0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (m_axi_gmem1_0_RVALID = ap_const_logic_0)) or ((m_axi_gmem1_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln199_fu_315_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln199_fu_315_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter12_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten_fu_116, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_116;
        end if; 
    end process;

    empty_75_fu_369_p0 <= empty_75_fu_369_p00(2 - 1 downto 0);
    empty_75_fu_369_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln199_1_fu_357_p3),4));
    empty_75_fu_369_p1 <= zext_ln193_cast_reg_510(2 - 1 downto 0);

    gmem1_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem1_0_ARREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem1_blk_n_AR <= m_axi_gmem1_0_ARREADY;
        else 
            gmem1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter12, m_axi_gmem1_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem1_blk_n_R <= m_axi_gmem1_0_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln199_fu_315_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = bound) else "0";
    icmp_ln200_fu_344_p2 <= "1" when (kw_fu_108 = kernel_h) else "0";
    local_weights_1_address0 <= zext_ln193_1_cast_reg_515(6 - 1 downto 0);
    local_weights_1_ce0 <= local_weights_1_ce0_local;

    local_weights_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_1_ce0_local <= ap_const_logic_1;
        else 
            local_weights_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_1_d0 <= trunc_ln203_1_fu_461_p1;
    local_weights_1_we0 <= local_weights_1_we0_local;

    local_weights_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, add_ln202_reg_533_pp0_iter12_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_lv4_1 = add_ln202_reg_533_pp0_iter12_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_1_we0_local <= ap_const_logic_1;
        else 
            local_weights_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_2_address0 <= zext_ln193_1_cast_reg_515(6 - 1 downto 0);
    local_weights_2_ce0 <= local_weights_2_ce0_local;

    local_weights_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_2_ce0_local <= ap_const_logic_1;
        else 
            local_weights_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_2_d0 <= trunc_ln203_1_fu_461_p1;
    local_weights_2_we0 <= local_weights_2_we0_local;

    local_weights_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, add_ln202_reg_533_pp0_iter12_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_lv4_2 = add_ln202_reg_533_pp0_iter12_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_2_we0_local <= ap_const_logic_1;
        else 
            local_weights_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_3_address0 <= zext_ln193_1_cast_reg_515(6 - 1 downto 0);
    local_weights_3_ce0 <= local_weights_3_ce0_local;

    local_weights_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_3_ce0_local <= ap_const_logic_1;
        else 
            local_weights_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_3_d0 <= trunc_ln203_1_fu_461_p1;
    local_weights_3_we0 <= local_weights_3_we0_local;

    local_weights_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, add_ln202_reg_533_pp0_iter12_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_lv4_3 = add_ln202_reg_533_pp0_iter12_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_3_we0_local <= ap_const_logic_1;
        else 
            local_weights_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_4_address0 <= zext_ln193_1_cast_reg_515(6 - 1 downto 0);
    local_weights_4_ce0 <= local_weights_4_ce0_local;

    local_weights_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_4_ce0_local <= ap_const_logic_1;
        else 
            local_weights_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_4_d0 <= trunc_ln203_1_fu_461_p1;
    local_weights_4_we0 <= local_weights_4_we0_local;

    local_weights_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, add_ln202_reg_533_pp0_iter12_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_lv4_4 = add_ln202_reg_533_pp0_iter12_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_4_we0_local <= ap_const_logic_1;
        else 
            local_weights_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_5_address0 <= zext_ln193_1_cast_reg_515(6 - 1 downto 0);
    local_weights_5_ce0 <= local_weights_5_ce0_local;

    local_weights_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_5_ce0_local <= ap_const_logic_1;
        else 
            local_weights_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_5_d0 <= trunc_ln203_1_fu_461_p1;
    local_weights_5_we0 <= local_weights_5_we0_local;

    local_weights_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, add_ln202_reg_533_pp0_iter12_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_lv4_5 = add_ln202_reg_533_pp0_iter12_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_5_we0_local <= ap_const_logic_1;
        else 
            local_weights_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_6_address0 <= zext_ln193_1_cast_reg_515(6 - 1 downto 0);
    local_weights_6_ce0 <= local_weights_6_ce0_local;

    local_weights_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_6_ce0_local <= ap_const_logic_1;
        else 
            local_weights_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_6_d0 <= trunc_ln203_1_fu_461_p1;
    local_weights_6_we0 <= local_weights_6_we0_local;

    local_weights_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, add_ln202_reg_533_pp0_iter12_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_lv4_6 = add_ln202_reg_533_pp0_iter12_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_6_we0_local <= ap_const_logic_1;
        else 
            local_weights_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_7_address0 <= zext_ln193_1_cast_reg_515(6 - 1 downto 0);
    local_weights_7_ce0 <= local_weights_7_ce0_local;

    local_weights_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_7_ce0_local <= ap_const_logic_1;
        else 
            local_weights_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_7_d0 <= trunc_ln203_1_fu_461_p1;
    local_weights_7_we0 <= local_weights_7_we0_local;

    local_weights_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, add_ln202_reg_533_pp0_iter12_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_lv4_7 = add_ln202_reg_533_pp0_iter12_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_7_we0_local <= ap_const_logic_1;
        else 
            local_weights_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_8_address0 <= zext_ln193_1_cast_reg_515(6 - 1 downto 0);
    local_weights_8_ce0 <= local_weights_8_ce0_local;

    local_weights_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_8_ce0_local <= ap_const_logic_1;
        else 
            local_weights_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_8_d0 <= trunc_ln203_1_fu_461_p1;
    local_weights_8_we0 <= local_weights_8_we0_local;

    local_weights_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, add_ln202_reg_533_pp0_iter12_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if ((not((ap_const_lv4_0 = add_ln202_reg_533_pp0_iter12_reg)) and not((ap_const_lv4_1 = add_ln202_reg_533_pp0_iter12_reg)) and not((ap_const_lv4_2 = add_ln202_reg_533_pp0_iter12_reg)) and not((ap_const_lv4_3 = add_ln202_reg_533_pp0_iter12_reg)) and not((ap_const_lv4_4 = add_ln202_reg_533_pp0_iter12_reg)) and not((ap_const_lv4_5 = add_ln202_reg_533_pp0_iter12_reg)) and not((ap_const_lv4_6 = add_ln202_reg_533_pp0_iter12_reg)) and not((ap_const_lv4_7 = add_ln202_reg_533_pp0_iter12_reg)) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_8_we0_local <= ap_const_logic_1;
        else 
            local_weights_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_address0 <= zext_ln193_1_cast_reg_515(6 - 1 downto 0);
    local_weights_ce0 <= local_weights_ce0_local;

    local_weights_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_ce0_local <= ap_const_logic_1;
        else 
            local_weights_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_d0 <= trunc_ln203_1_fu_461_p1;
    local_weights_we0 <= local_weights_we0_local;

    local_weights_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, add_ln202_reg_533_pp0_iter12_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_lv4_0 = add_ln202_reg_533_pp0_iter12_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            local_weights_we0_local <= ap_const_logic_1;
        else 
            local_weights_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln203_fu_456_p2 <= std_logic_vector(shift_right(unsigned(gmem1_addr_read_reg_554),to_integer(unsigned('0' & zext_ln203_1_fu_452_p1(31-1 downto 0)))));
    m_axi_gmem1_0_ARADDR <= gmem1_addr_reg_543;
    m_axi_gmem1_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_ARID <= ap_const_lv1_0;
    m_axi_gmem1_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_gmem1_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem1_0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem1_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_AWID <= ap_const_lv1_0;
    m_axi_gmem1_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_0_BREADY <= ap_const_logic_0;

    m_axi_gmem1_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem1_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_0_WID <= ap_const_lv1_0;
    m_axi_gmem1_0_WLAST <= ap_const_logic_0;
    m_axi_gmem1_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_WVALID <= ap_const_logic_0;
    mul_ln202_fu_403_p0 <= mul_ln202_fu_403_p00(4 - 1 downto 0);
    mul_ln202_fu_403_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln202_reg_533),10));
    mul_ln202_fu_403_p1 <= p_cast_reg_505(7 - 1 downto 0);
    p_cast_fu_285_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty),10));
    select_ln199_1_fu_357_p3 <= 
        add_ln199_fu_338_p2 when (icmp_ln200_fu_344_p2(0) = '1') else 
        kh_fu_112;
    select_ln199_fu_349_p3 <= 
        ap_const_lv2_0 when (icmp_ln200_fu_344_p2(0) = '1') else 
        kw_fu_108;
        sext_ln203_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln203_2_fu_421_p4),64));

    shl_ln_fu_445_p3 <= (trunc_ln203_reg_549_pp0_iter12_reg & ap_const_lv3_0);
    trunc_ln203_1_fu_461_p1 <= lshr_ln203_fu_456_p2(8 - 1 downto 0);
    trunc_ln203_2_fu_421_p4 <= add_ln203_fu_416_p2(63 downto 2);
    trunc_ln203_fu_441_p1 <= add_ln203_fu_416_p2(2 - 1 downto 0);
    zext_ln193_1_cast_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln193_1),64));
    zext_ln193_cast_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln193),4));
    zext_ln200_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln199_fu_349_p3),4));
    zext_ln203_1_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_445_p3),32));
    zext_ln203_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln202_reg_538),64));
end behav;
