// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv2d_blck_compute_depthwise_Pipeline_VITIS_LOOP_199_1_VITIS_LOOP_200_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER,
        bound,
        local_weights_address0,
        local_weights_ce0,
        local_weights_we0,
        local_weights_d0,
        zext_ln193_1,
        local_weights_1_address0,
        local_weights_1_ce0,
        local_weights_1_we0,
        local_weights_1_d0,
        local_weights_2_address0,
        local_weights_2_ce0,
        local_weights_2_we0,
        local_weights_2_d0,
        local_weights_3_address0,
        local_weights_3_ce0,
        local_weights_3_we0,
        local_weights_3_d0,
        local_weights_4_address0,
        local_weights_4_ce0,
        local_weights_4_we0,
        local_weights_4_d0,
        local_weights_5_address0,
        local_weights_5_ce0,
        local_weights_5_we0,
        local_weights_5_d0,
        local_weights_6_address0,
        local_weights_6_ce0,
        local_weights_6_we0,
        local_weights_6_d0,
        local_weights_7_address0,
        local_weights_7_ce0,
        local_weights_7_we0,
        local_weights_7_d0,
        local_weights_8_address0,
        local_weights_8_ce0,
        local_weights_8_we0,
        local_weights_8_d0,
        kernel_h,
        zext_ln193,
        empty,
        filter_data
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_0_AWVALID;
input   m_axi_gmem1_0_AWREADY;
output  [63:0] m_axi_gmem1_0_AWADDR;
output  [0:0] m_axi_gmem1_0_AWID;
output  [31:0] m_axi_gmem1_0_AWLEN;
output  [2:0] m_axi_gmem1_0_AWSIZE;
output  [1:0] m_axi_gmem1_0_AWBURST;
output  [1:0] m_axi_gmem1_0_AWLOCK;
output  [3:0] m_axi_gmem1_0_AWCACHE;
output  [2:0] m_axi_gmem1_0_AWPROT;
output  [3:0] m_axi_gmem1_0_AWQOS;
output  [3:0] m_axi_gmem1_0_AWREGION;
output  [0:0] m_axi_gmem1_0_AWUSER;
output   m_axi_gmem1_0_WVALID;
input   m_axi_gmem1_0_WREADY;
output  [31:0] m_axi_gmem1_0_WDATA;
output  [3:0] m_axi_gmem1_0_WSTRB;
output   m_axi_gmem1_0_WLAST;
output  [0:0] m_axi_gmem1_0_WID;
output  [0:0] m_axi_gmem1_0_WUSER;
output   m_axi_gmem1_0_ARVALID;
input   m_axi_gmem1_0_ARREADY;
output  [63:0] m_axi_gmem1_0_ARADDR;
output  [0:0] m_axi_gmem1_0_ARID;
output  [31:0] m_axi_gmem1_0_ARLEN;
output  [2:0] m_axi_gmem1_0_ARSIZE;
output  [1:0] m_axi_gmem1_0_ARBURST;
output  [1:0] m_axi_gmem1_0_ARLOCK;
output  [3:0] m_axi_gmem1_0_ARCACHE;
output  [2:0] m_axi_gmem1_0_ARPROT;
output  [3:0] m_axi_gmem1_0_ARQOS;
output  [3:0] m_axi_gmem1_0_ARREGION;
output  [0:0] m_axi_gmem1_0_ARUSER;
input   m_axi_gmem1_0_RVALID;
output   m_axi_gmem1_0_RREADY;
input  [31:0] m_axi_gmem1_0_RDATA;
input   m_axi_gmem1_0_RLAST;
input  [0:0] m_axi_gmem1_0_RID;
input  [8:0] m_axi_gmem1_0_RFIFONUM;
input  [0:0] m_axi_gmem1_0_RUSER;
input  [1:0] m_axi_gmem1_0_RRESP;
input   m_axi_gmem1_0_BVALID;
output   m_axi_gmem1_0_BREADY;
input  [1:0] m_axi_gmem1_0_BRESP;
input  [0:0] m_axi_gmem1_0_BID;
input  [0:0] m_axi_gmem1_0_BUSER;
input  [3:0] bound;
output  [5:0] local_weights_address0;
output   local_weights_ce0;
output   local_weights_we0;
output  [7:0] local_weights_d0;
input  [5:0] zext_ln193_1;
output  [5:0] local_weights_1_address0;
output   local_weights_1_ce0;
output   local_weights_1_we0;
output  [7:0] local_weights_1_d0;
output  [5:0] local_weights_2_address0;
output   local_weights_2_ce0;
output   local_weights_2_we0;
output  [7:0] local_weights_2_d0;
output  [5:0] local_weights_3_address0;
output   local_weights_3_ce0;
output   local_weights_3_we0;
output  [7:0] local_weights_3_d0;
output  [5:0] local_weights_4_address0;
output   local_weights_4_ce0;
output   local_weights_4_we0;
output  [7:0] local_weights_4_d0;
output  [5:0] local_weights_5_address0;
output   local_weights_5_ce0;
output   local_weights_5_we0;
output  [7:0] local_weights_5_d0;
output  [5:0] local_weights_6_address0;
output   local_weights_6_ce0;
output   local_weights_6_we0;
output  [7:0] local_weights_6_d0;
output  [5:0] local_weights_7_address0;
output   local_weights_7_ce0;
output   local_weights_7_we0;
output  [7:0] local_weights_7_d0;
output  [5:0] local_weights_8_address0;
output   local_weights_8_ce0;
output   local_weights_8_we0;
output  [7:0] local_weights_8_d0;
input  [1:0] kernel_h;
input  [1:0] zext_ln193;
input  [6:0] empty;
input  [63:0] filter_data;

reg ap_idle;
reg m_axi_gmem1_0_ARVALID;
reg m_axi_gmem1_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln199_fu_315_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    gmem1_blk_n_R;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [9:0] p_cast_fu_285_p1;
reg   [9:0] p_cast_reg_505;
wire   [3:0] zext_ln193_cast_fu_289_p1;
reg   [3:0] zext_ln193_cast_reg_510;
wire   [63:0] zext_ln193_1_cast_fu_293_p1;
reg   [63:0] zext_ln193_1_cast_reg_515;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] add_ln202_fu_378_p2;
reg   [3:0] add_ln202_reg_533;
reg   [3:0] add_ln202_reg_533_pp0_iter2_reg;
reg   [3:0] add_ln202_reg_533_pp0_iter3_reg;
reg   [3:0] add_ln202_reg_533_pp0_iter4_reg;
reg   [3:0] add_ln202_reg_533_pp0_iter5_reg;
reg   [3:0] add_ln202_reg_533_pp0_iter6_reg;
reg   [3:0] add_ln202_reg_533_pp0_iter7_reg;
reg   [3:0] add_ln202_reg_533_pp0_iter8_reg;
reg   [3:0] add_ln202_reg_533_pp0_iter9_reg;
reg   [3:0] add_ln202_reg_533_pp0_iter10_reg;
reg   [3:0] add_ln202_reg_533_pp0_iter11_reg;
reg   [3:0] add_ln202_reg_533_pp0_iter12_reg;
wire   [9:0] mul_ln202_fu_403_p2;
reg   [9:0] mul_ln202_reg_538;
reg   [63:0] gmem1_addr_reg_543;
wire   [1:0] trunc_ln203_fu_441_p1;
reg   [1:0] trunc_ln203_reg_549;
reg   [1:0] trunc_ln203_reg_549_pp0_iter4_reg;
reg   [1:0] trunc_ln203_reg_549_pp0_iter5_reg;
reg   [1:0] trunc_ln203_reg_549_pp0_iter6_reg;
reg   [1:0] trunc_ln203_reg_549_pp0_iter7_reg;
reg   [1:0] trunc_ln203_reg_549_pp0_iter8_reg;
reg   [1:0] trunc_ln203_reg_549_pp0_iter9_reg;
reg   [1:0] trunc_ln203_reg_549_pp0_iter10_reg;
reg   [1:0] trunc_ln203_reg_549_pp0_iter11_reg;
reg   [1:0] trunc_ln203_reg_549_pp0_iter12_reg;
reg   [31:0] gmem1_addr_read_reg_554;
wire    ap_block_pp0_stage0_grp0;
wire  signed [63:0] sext_ln203_fu_431_p1;
reg   [1:0] kw_fu_108;
wire   [1:0] add_ln200_fu_384_p2;
wire    ap_loop_init;
reg   [1:0] kh_fu_112;
wire   [1:0] select_ln199_1_fu_357_p3;
reg   [3:0] indvar_flatten_fu_116;
wire   [3:0] add_ln199_1_fu_321_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg    local_weights_7_we0_local;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [7:0] trunc_ln203_1_fu_461_p1;
reg    local_weights_7_ce0_local;
reg    local_weights_6_we0_local;
reg    local_weights_6_ce0_local;
reg    local_weights_5_we0_local;
reg    local_weights_5_ce0_local;
reg    local_weights_4_we0_local;
reg    local_weights_4_ce0_local;
reg    local_weights_3_we0_local;
reg    local_weights_3_ce0_local;
reg    local_weights_2_we0_local;
reg    local_weights_2_ce0_local;
reg    local_weights_1_we0_local;
reg    local_weights_1_ce0_local;
reg    local_weights_we0_local;
reg    local_weights_ce0_local;
reg    local_weights_8_we0_local;
reg    local_weights_8_ce0_local;
wire   [0:0] icmp_ln200_fu_344_p2;
wire   [1:0] add_ln199_fu_338_p2;
wire   [1:0] empty_75_fu_369_p0;
wire   [1:0] empty_75_fu_369_p1;
wire   [1:0] select_ln199_fu_349_p3;
wire   [3:0] zext_ln200_fu_374_p1;
wire   [3:0] empty_75_fu_369_p2;
wire   [3:0] mul_ln202_fu_403_p0;
wire   [6:0] mul_ln202_fu_403_p1;
wire   [63:0] zext_ln203_fu_408_p1;
wire   [63:0] add_ln203_1_fu_411_p2;
wire   [63:0] add_ln203_fu_416_p2;
wire   [61:0] trunc_ln203_2_fu_421_p4;
wire   [4:0] shl_ln_fu_445_p3;
wire   [31:0] zext_ln203_1_fu_452_p1;
wire   [31:0] lshr_ln203_fu_456_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] empty_75_fu_369_p00;
wire   [9:0] mul_ln202_fu_403_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 kw_fu_108 = 2'd0;
#0 kh_fu_112 = 2'd0;
#0 indvar_flatten_fu_116 = 4'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv2d_blck_mul_2ns_2ns_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2ns_4_1_1_U1(
    .din0(empty_75_fu_369_p0),
    .din1(empty_75_fu_369_p1),
    .dout(empty_75_fu_369_p2)
);

conv2d_blck_mul_4ns_7ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mul_4ns_7ns_10_1_1_U2(
    .din0(mul_ln202_fu_403_p0),
    .din1(mul_ln202_fu_403_p1),
    .dout(mul_ln202_fu_403_p2)
);

conv2d_blck_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln199_fu_315_p2 == 1'd0))) begin
            indvar_flatten_fu_116 <= add_ln199_1_fu_321_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_116 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            kh_fu_112 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            kh_fu_112 <= select_ln199_1_fu_357_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            kw_fu_108 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            kw_fu_108 <= add_ln200_fu_384_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        add_ln202_reg_533 <= add_ln202_fu_378_p2;
        p_cast_reg_505[6 : 0] <= p_cast_fu_285_p1[6 : 0];
        zext_ln193_1_cast_reg_515[5 : 0] <= zext_ln193_1_cast_fu_293_p1[5 : 0];
        zext_ln193_cast_reg_510[1 : 0] <= zext_ln193_cast_fu_289_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln202_reg_533_pp0_iter10_reg <= add_ln202_reg_533_pp0_iter9_reg;
        add_ln202_reg_533_pp0_iter11_reg <= add_ln202_reg_533_pp0_iter10_reg;
        add_ln202_reg_533_pp0_iter12_reg <= add_ln202_reg_533_pp0_iter11_reg;
        add_ln202_reg_533_pp0_iter2_reg <= add_ln202_reg_533;
        add_ln202_reg_533_pp0_iter3_reg <= add_ln202_reg_533_pp0_iter2_reg;
        add_ln202_reg_533_pp0_iter4_reg <= add_ln202_reg_533_pp0_iter3_reg;
        add_ln202_reg_533_pp0_iter5_reg <= add_ln202_reg_533_pp0_iter4_reg;
        add_ln202_reg_533_pp0_iter6_reg <= add_ln202_reg_533_pp0_iter5_reg;
        add_ln202_reg_533_pp0_iter7_reg <= add_ln202_reg_533_pp0_iter6_reg;
        add_ln202_reg_533_pp0_iter8_reg <= add_ln202_reg_533_pp0_iter7_reg;
        add_ln202_reg_533_pp0_iter9_reg <= add_ln202_reg_533_pp0_iter8_reg;
        gmem1_addr_read_reg_554 <= m_axi_gmem1_0_RDATA;
        gmem1_addr_reg_543 <= sext_ln203_fu_431_p1;
        mul_ln202_reg_538 <= mul_ln202_fu_403_p2;
        trunc_ln203_reg_549 <= trunc_ln203_fu_441_p1;
        trunc_ln203_reg_549_pp0_iter10_reg <= trunc_ln203_reg_549_pp0_iter9_reg;
        trunc_ln203_reg_549_pp0_iter11_reg <= trunc_ln203_reg_549_pp0_iter10_reg;
        trunc_ln203_reg_549_pp0_iter12_reg <= trunc_ln203_reg_549_pp0_iter11_reg;
        trunc_ln203_reg_549_pp0_iter4_reg <= trunc_ln203_reg_549;
        trunc_ln203_reg_549_pp0_iter5_reg <= trunc_ln203_reg_549_pp0_iter4_reg;
        trunc_ln203_reg_549_pp0_iter6_reg <= trunc_ln203_reg_549_pp0_iter5_reg;
        trunc_ln203_reg_549_pp0_iter7_reg <= trunc_ln203_reg_549_pp0_iter6_reg;
        trunc_ln203_reg_549_pp0_iter8_reg <= trunc_ln203_reg_549_pp0_iter7_reg;
        trunc_ln203_reg_549_pp0_iter9_reg <= trunc_ln203_reg_549_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln199_fu_315_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_116;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem1_blk_n_AR = m_axi_gmem1_0_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem1_blk_n_R = m_axi_gmem1_0_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_1_ce0_local = 1'b1;
    end else begin
        local_weights_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (4'd1 == add_ln202_reg_533_pp0_iter12_reg) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_1_we0_local = 1'b1;
    end else begin
        local_weights_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_2_ce0_local = 1'b1;
    end else begin
        local_weights_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (4'd2 == add_ln202_reg_533_pp0_iter12_reg) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_2_we0_local = 1'b1;
    end else begin
        local_weights_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_3_ce0_local = 1'b1;
    end else begin
        local_weights_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (4'd3 == add_ln202_reg_533_pp0_iter12_reg) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_3_we0_local = 1'b1;
    end else begin
        local_weights_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_4_ce0_local = 1'b1;
    end else begin
        local_weights_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (4'd4 == add_ln202_reg_533_pp0_iter12_reg) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_4_we0_local = 1'b1;
    end else begin
        local_weights_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_5_ce0_local = 1'b1;
    end else begin
        local_weights_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (4'd5 == add_ln202_reg_533_pp0_iter12_reg) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_5_we0_local = 1'b1;
    end else begin
        local_weights_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_6_ce0_local = 1'b1;
    end else begin
        local_weights_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (4'd6 == add_ln202_reg_533_pp0_iter12_reg) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_6_we0_local = 1'b1;
    end else begin
        local_weights_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_7_ce0_local = 1'b1;
    end else begin
        local_weights_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (4'd7 == add_ln202_reg_533_pp0_iter12_reg) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_7_we0_local = 1'b1;
    end else begin
        local_weights_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_8_ce0_local = 1'b1;
    end else begin
        local_weights_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(4'd0 == add_ln202_reg_533_pp0_iter12_reg) & ~(4'd1 == add_ln202_reg_533_pp0_iter12_reg) & ~(4'd2 == add_ln202_reg_533_pp0_iter12_reg) & ~(4'd3 == add_ln202_reg_533_pp0_iter12_reg) & ~(4'd4 == add_ln202_reg_533_pp0_iter12_reg) & ~(4'd5 == add_ln202_reg_533_pp0_iter12_reg) & ~(4'd6 == add_ln202_reg_533_pp0_iter12_reg) & ~(4'd7 == add_ln202_reg_533_pp0_iter12_reg) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_8_we0_local = 1'b1;
    end else begin
        local_weights_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_ce0_local = 1'b1;
    end else begin
        local_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (4'd0 == add_ln202_reg_533_pp0_iter12_reg) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_weights_we0_local = 1'b1;
    end else begin
        local_weights_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem1_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem1_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln199_1_fu_321_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln199_fu_338_p2 = (kh_fu_112 + 2'd1);

assign add_ln200_fu_384_p2 = (select_ln199_fu_349_p3 + 2'd1);

assign add_ln202_fu_378_p2 = (zext_ln200_fu_374_p1 + empty_75_fu_369_p2);

assign add_ln203_1_fu_411_p2 = (zext_ln203_fu_408_p1 + filter_data);

assign add_ln203_fu_416_p2 = (add_ln203_1_fu_411_p2 + zext_ln193_1_cast_reg_515);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter12 == 1'b1) & (m_axi_gmem1_0_RVALID == 1'b0)) | ((m_axi_gmem1_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter12 == 1'b1) & (m_axi_gmem1_0_RVALID == 1'b0)) | ((m_axi_gmem1_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter12 == 1'b1) & (m_axi_gmem1_0_RVALID == 1'b0)) | ((m_axi_gmem1_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_75_fu_369_p0 = empty_75_fu_369_p00;

assign empty_75_fu_369_p00 = select_ln199_1_fu_357_p3;

assign empty_75_fu_369_p1 = zext_ln193_cast_reg_510;

assign icmp_ln199_fu_315_p2 = ((ap_sig_allocacmp_indvar_flatten_load == bound) ? 1'b1 : 1'b0);

assign icmp_ln200_fu_344_p2 = ((kw_fu_108 == kernel_h) ? 1'b1 : 1'b0);

assign local_weights_1_address0 = zext_ln193_1_cast_reg_515;

assign local_weights_1_ce0 = local_weights_1_ce0_local;

assign local_weights_1_d0 = trunc_ln203_1_fu_461_p1;

assign local_weights_1_we0 = local_weights_1_we0_local;

assign local_weights_2_address0 = zext_ln193_1_cast_reg_515;

assign local_weights_2_ce0 = local_weights_2_ce0_local;

assign local_weights_2_d0 = trunc_ln203_1_fu_461_p1;

assign local_weights_2_we0 = local_weights_2_we0_local;

assign local_weights_3_address0 = zext_ln193_1_cast_reg_515;

assign local_weights_3_ce0 = local_weights_3_ce0_local;

assign local_weights_3_d0 = trunc_ln203_1_fu_461_p1;

assign local_weights_3_we0 = local_weights_3_we0_local;

assign local_weights_4_address0 = zext_ln193_1_cast_reg_515;

assign local_weights_4_ce0 = local_weights_4_ce0_local;

assign local_weights_4_d0 = trunc_ln203_1_fu_461_p1;

assign local_weights_4_we0 = local_weights_4_we0_local;

assign local_weights_5_address0 = zext_ln193_1_cast_reg_515;

assign local_weights_5_ce0 = local_weights_5_ce0_local;

assign local_weights_5_d0 = trunc_ln203_1_fu_461_p1;

assign local_weights_5_we0 = local_weights_5_we0_local;

assign local_weights_6_address0 = zext_ln193_1_cast_reg_515;

assign local_weights_6_ce0 = local_weights_6_ce0_local;

assign local_weights_6_d0 = trunc_ln203_1_fu_461_p1;

assign local_weights_6_we0 = local_weights_6_we0_local;

assign local_weights_7_address0 = zext_ln193_1_cast_reg_515;

assign local_weights_7_ce0 = local_weights_7_ce0_local;

assign local_weights_7_d0 = trunc_ln203_1_fu_461_p1;

assign local_weights_7_we0 = local_weights_7_we0_local;

assign local_weights_8_address0 = zext_ln193_1_cast_reg_515;

assign local_weights_8_ce0 = local_weights_8_ce0_local;

assign local_weights_8_d0 = trunc_ln203_1_fu_461_p1;

assign local_weights_8_we0 = local_weights_8_we0_local;

assign local_weights_address0 = zext_ln193_1_cast_reg_515;

assign local_weights_ce0 = local_weights_ce0_local;

assign local_weights_d0 = trunc_ln203_1_fu_461_p1;

assign local_weights_we0 = local_weights_we0_local;

assign lshr_ln203_fu_456_p2 = gmem1_addr_read_reg_554 >> zext_ln203_1_fu_452_p1;

assign m_axi_gmem1_0_ARADDR = gmem1_addr_reg_543;

assign m_axi_gmem1_0_ARBURST = 2'd0;

assign m_axi_gmem1_0_ARCACHE = 4'd0;

assign m_axi_gmem1_0_ARID = 1'd0;

assign m_axi_gmem1_0_ARLEN = 64'd1;

assign m_axi_gmem1_0_ARLOCK = 2'd0;

assign m_axi_gmem1_0_ARPROT = 3'd0;

assign m_axi_gmem1_0_ARQOS = 4'd0;

assign m_axi_gmem1_0_ARREGION = 4'd0;

assign m_axi_gmem1_0_ARSIZE = 3'd0;

assign m_axi_gmem1_0_ARUSER = 1'd0;

assign m_axi_gmem1_0_AWADDR = 64'd0;

assign m_axi_gmem1_0_AWBURST = 2'd0;

assign m_axi_gmem1_0_AWCACHE = 4'd0;

assign m_axi_gmem1_0_AWID = 1'd0;

assign m_axi_gmem1_0_AWLEN = 32'd0;

assign m_axi_gmem1_0_AWLOCK = 2'd0;

assign m_axi_gmem1_0_AWPROT = 3'd0;

assign m_axi_gmem1_0_AWQOS = 4'd0;

assign m_axi_gmem1_0_AWREGION = 4'd0;

assign m_axi_gmem1_0_AWSIZE = 3'd0;

assign m_axi_gmem1_0_AWUSER = 1'd0;

assign m_axi_gmem1_0_AWVALID = 1'b0;

assign m_axi_gmem1_0_BREADY = 1'b0;

assign m_axi_gmem1_0_WDATA = 32'd0;

assign m_axi_gmem1_0_WID = 1'd0;

assign m_axi_gmem1_0_WLAST = 1'b0;

assign m_axi_gmem1_0_WSTRB = 4'd0;

assign m_axi_gmem1_0_WUSER = 1'd0;

assign m_axi_gmem1_0_WVALID = 1'b0;

assign mul_ln202_fu_403_p0 = mul_ln202_fu_403_p00;

assign mul_ln202_fu_403_p00 = add_ln202_reg_533;

assign mul_ln202_fu_403_p1 = p_cast_reg_505;

assign p_cast_fu_285_p1 = empty;

assign select_ln199_1_fu_357_p3 = ((icmp_ln200_fu_344_p2[0:0] == 1'b1) ? add_ln199_fu_338_p2 : kh_fu_112);

assign select_ln199_fu_349_p3 = ((icmp_ln200_fu_344_p2[0:0] == 1'b1) ? 2'd0 : kw_fu_108);

assign sext_ln203_fu_431_p1 = $signed(trunc_ln203_2_fu_421_p4);

assign shl_ln_fu_445_p3 = {{trunc_ln203_reg_549_pp0_iter12_reg}, {3'd0}};

assign trunc_ln203_1_fu_461_p1 = lshr_ln203_fu_456_p2[7:0];

assign trunc_ln203_2_fu_421_p4 = {{add_ln203_fu_416_p2[63:2]}};

assign trunc_ln203_fu_441_p1 = add_ln203_fu_416_p2[1:0];

assign zext_ln193_1_cast_fu_293_p1 = zext_ln193_1;

assign zext_ln193_cast_fu_289_p1 = zext_ln193;

assign zext_ln200_fu_374_p1 = select_ln199_fu_349_p3;

assign zext_ln203_1_fu_452_p1 = shl_ln_fu_445_p3;

assign zext_ln203_fu_408_p1 = mul_ln202_reg_538;

always @ (posedge ap_clk) begin
    p_cast_reg_505[9:7] <= 3'b000;
    zext_ln193_cast_reg_510[3:2] <= 2'b00;
    zext_ln193_1_cast_reg_515[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //conv2d_blck_compute_depthwise_Pipeline_VITIS_LOOP_199_1_VITIS_LOOP_200_2
