// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_blck_conv2d_blck,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35ti-csg324-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=78,HLS_SYN_DSP=0,HLS_SYN_FF=18805,HLS_SYN_LUT=24009,HLS_VERSION=2024_2}" *)

module conv2d_blck (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [0:0] out_stream_TKEEP;
output  [0:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_data;
wire   [63:0] filter_data;
wire   [63:0] bias_data;
wire   [63:0] multiplier_data;
wire   [63:0] shift_data;
wire   [63:0] output_data;
wire   [31:0] conv_type;
wire   [31:0] h_in;
wire   [31:0] w_in;
wire   [31:0] c_in;
wire   [31:0] c_out;
wire   [31:0] h_out;
wire   [31:0] w_out;
wire   [31:0] stride;
wire   [31:0] padding;
wire   [31:0] input_offset;
wire   [31:0] weights_offset;
wire   [31:0] output_offset;
wire   [31:0] act_min;
wire   [31:0] act_max;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state10;
reg   [31:0] act_max_read_reg_523;
reg   [31:0] act_min_read_reg_530;
reg   [31:0] output_offset_read_reg_537;
reg   [31:0] weights_offset_read_reg_544;
reg   [31:0] input_offset_read_reg_551;
reg   [31:0] stride_read_reg_558;
reg  signed [31:0] w_out_read_reg_564;
reg   [31:0] h_out_read_reg_572;
reg  signed [31:0] c_out_read_reg_580;
reg   [31:0] c_in_read_reg_588;
reg   [31:0] w_in_read_reg_595;
reg   [31:0] h_in_read_reg_602;
wire   [31:0] conv_type_read_read_fu_240_p2;
reg   [31:0] conv_type_read_reg_608;
reg   [63:0] output_data_read_reg_612;
reg   [63:0] shift_data_read_reg_621;
reg   [63:0] multiplier_data_read_reg_628;
reg   [63:0] bias_data_read_reg_635;
reg   [63:0] filter_data_read_reg_642;
reg   [63:0] input_data_read_reg_649;
wire   [1:0] kernel_h_fu_465_p3;
reg   [1:0] kernel_h_reg_659;
wire   [0:0] pad_w_fu_485_p2;
reg   [0:0] pad_w_reg_665;
wire  signed [31:0] grp_fu_389_p2;
reg  signed [31:0] mul_ln367_reg_671;
wire    ap_CS_fsm_state6;
wire   [31:0] grp_fu_385_p2;
reg   [31:0] out_elems_reg_676;
wire    ap_CS_fsm_state8;
wire   [30:0] trunc_ln369_fu_491_p1;
reg   [30:0] trunc_ln369_reg_683;
wire   [30:0] empty_fu_500_p3;
reg   [30:0] empty_reg_688;
wire    ap_CS_fsm_state9;
wire   [63:0] zext_ln369_fu_513_p1;
wire   [31:0] sub_fu_517_p2;
reg   [31:0] sub_reg_703;
wire    ap_CS_fsm_state18;
wire    grp_compute_depthwise_fu_288_ap_start;
wire    grp_compute_depthwise_fu_288_ap_done;
wire    grp_compute_depthwise_fu_288_ap_idle;
wire    grp_compute_depthwise_fu_288_ap_ready;
wire    grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWID;
wire   [31:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWUSER;
wire    grp_compute_depthwise_fu_288_m_axi_gmem0_0_WVALID;
wire   [7:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_WDATA;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_WSTRB;
wire    grp_compute_depthwise_fu_288_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_WID;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_WUSER;
wire    grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARID;
wire   [31:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARUSER;
wire    grp_compute_depthwise_fu_288_m_axi_gmem0_0_RREADY;
wire    grp_compute_depthwise_fu_288_m_axi_gmem0_0_BREADY;
wire    grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWID;
wire   [31:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWUSER;
wire    grp_compute_depthwise_fu_288_m_axi_gmem1_0_WVALID;
wire   [31:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_WDATA;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_WSTRB;
wire    grp_compute_depthwise_fu_288_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_WID;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_WUSER;
wire    grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARID;
wire   [31:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARUSER;
wire    grp_compute_depthwise_fu_288_m_axi_gmem1_0_RREADY;
wire    grp_compute_depthwise_fu_288_m_axi_gmem1_0_BREADY;
wire  signed [31:0] grp_compute_depthwise_fu_288_grp_fu_385_p_din0;
wire  signed [31:0] grp_compute_depthwise_fu_288_grp_fu_385_p_din1;
wire    grp_compute_depthwise_fu_288_grp_fu_385_p_ce;
wire    grp_compute_pointwise_fu_316_ap_start;
wire    grp_compute_pointwise_fu_316_ap_done;
wire    grp_compute_pointwise_fu_316_ap_idle;
wire    grp_compute_pointwise_fu_316_ap_ready;
wire    grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWID;
wire   [31:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWUSER;
wire    grp_compute_pointwise_fu_316_m_axi_gmem0_0_WVALID;
wire   [7:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_WDATA;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_WSTRB;
wire    grp_compute_pointwise_fu_316_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_WID;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_WUSER;
wire    grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARID;
wire   [31:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARUSER;
wire    grp_compute_pointwise_fu_316_m_axi_gmem0_0_RREADY;
wire    grp_compute_pointwise_fu_316_m_axi_gmem0_0_BREADY;
wire    grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWID;
wire   [31:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWUSER;
wire    grp_compute_pointwise_fu_316_m_axi_gmem1_0_WVALID;
wire   [31:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_WDATA;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_WSTRB;
wire    grp_compute_pointwise_fu_316_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_WID;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_WUSER;
wire    grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARID;
wire   [31:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARUSER;
wire    grp_compute_pointwise_fu_316_m_axi_gmem1_0_RREADY;
wire    grp_compute_pointwise_fu_316_m_axi_gmem1_0_BREADY;
wire    grp_compute_standard_fu_340_ap_start;
wire    grp_compute_standard_fu_340_ap_done;
wire    grp_compute_standard_fu_340_ap_idle;
wire    grp_compute_standard_fu_340_ap_ready;
wire    grp_compute_standard_fu_340_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWID;
wire   [31:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem0_0_AWUSER;
wire    grp_compute_standard_fu_340_m_axi_gmem0_0_WVALID;
wire   [7:0] grp_compute_standard_fu_340_m_axi_gmem0_0_WDATA;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem0_0_WSTRB;
wire    grp_compute_standard_fu_340_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem0_0_WID;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem0_0_WUSER;
wire    grp_compute_standard_fu_340_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARID;
wire   [31:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem0_0_ARUSER;
wire    grp_compute_standard_fu_340_m_axi_gmem0_0_RREADY;
wire    grp_compute_standard_fu_340_m_axi_gmem0_0_BREADY;
wire    grp_compute_standard_fu_340_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWID;
wire   [31:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem1_0_AWUSER;
wire    grp_compute_standard_fu_340_m_axi_gmem1_0_WVALID;
wire   [31:0] grp_compute_standard_fu_340_m_axi_gmem1_0_WDATA;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem1_0_WSTRB;
wire    grp_compute_standard_fu_340_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem1_0_WID;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem1_0_WUSER;
wire    grp_compute_standard_fu_340_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARID;
wire   [31:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_compute_standard_fu_340_m_axi_gmem1_0_ARUSER;
wire    grp_compute_standard_fu_340_m_axi_gmem1_0_RREADY;
wire    grp_compute_standard_fu_340_m_axi_gmem1_0_BREADY;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_start;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_done;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_idle;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_ready;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWID;
wire   [31:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWUSER;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WVALID;
wire   [7:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WDATA;
wire   [0:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WSTRB;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WID;
wire   [0:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WUSER;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARID;
wire   [31:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARUSER;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_RREADY;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_BREADY;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TREADY;
wire   [7:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TDATA;
wire    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID;
wire   [0:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TKEEP;
wire   [0:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TSTRB;
wire   [0:0] grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TLAST;
reg    gmem0_0_AWVALID;
wire    gmem0_0_AWREADY;
reg   [63:0] gmem0_0_AWADDR;
reg   [31:0] gmem0_0_AWLEN;
reg    gmem0_0_WVALID;
wire    gmem0_0_WREADY;
reg   [7:0] gmem0_0_WDATA;
reg   [0:0] gmem0_0_WSTRB;
reg    gmem0_0_ARVALID;
wire    gmem0_0_ARREADY;
reg   [63:0] gmem0_0_ARADDR;
reg   [31:0] gmem0_0_ARLEN;
wire    gmem0_0_RVALID;
reg    gmem0_0_RREADY;
wire   [7:0] gmem0_0_RDATA;
wire   [10:0] gmem0_0_RFIFONUM;
wire    gmem0_0_BVALID;
reg    gmem0_0_BREADY;
wire    gmem1_0_AWREADY;
wire    gmem1_0_WREADY;
reg    gmem1_0_ARVALID;
wire    gmem1_0_ARREADY;
reg   [63:0] gmem1_0_ARADDR;
reg   [31:0] gmem1_0_ARLEN;
wire    gmem1_0_RVALID;
reg    gmem1_0_RREADY;
wire   [31:0] gmem1_0_RDATA;
wire   [8:0] gmem1_0_RFIFONUM;
wire    gmem1_0_BVALID;
reg    grp_compute_depthwise_fu_288_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_compute_pointwise_fu_316_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_compute_standard_fu_340_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_start_reg;
wire    ap_CS_fsm_state19;
reg   [7:0] out_stream_TDATA_reg;
reg   [0:0] out_stream_TKEEP_reg;
reg   [0:0] out_stream_TSTRB_reg;
reg   [0:0] out_stream_TLAST_reg;
reg  signed [31:0] grp_fu_385_p0;
reg  signed [31:0] grp_fu_385_p1;
wire    ap_CS_fsm_state7;
wire  signed [31:0] icmp_ln310_fu_411_p0;
wire  signed [31:0] icmp_ln311_fu_417_p0;
wire  signed [31:0] icmp_ln312_fu_423_p0;
wire   [0:0] icmp_ln308_fu_399_p2;
wire   [0:0] icmp_ln309_fu_405_p2;
wire   [0:0] or_ln307_fu_429_p2;
wire   [0:0] icmp_ln307_fu_393_p2;
wire   [0:0] icmp_ln311_fu_417_p2;
wire   [0:0] icmp_ln312_fu_423_p2;
wire   [0:0] or_ln307_2_fu_441_p2;
wire   [0:0] icmp_ln310_fu_411_p2;
wire   [0:0] or_ln307_3_fu_447_p2;
wire   [0:0] or_ln307_1_fu_435_p2;
wire   [0:0] icmp_ln321_fu_459_p2;
wire   [0:0] icmp_ln326_fu_473_p2;
wire   [0:0] pad_h_1_fu_479_p2;
wire   [0:0] icmp_ln369_fu_495_p2;
reg    grp_fu_385_ce;
reg    grp_fu_389_ce;
reg    ap_predicate_op130_call_state3;
reg    ap_block_state3_on_subcall_done;
wire   [0:0] or_ln307_4_fu_453_p2;
wire    ap_CS_fsm_state20;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg   [7:0] out_stream_TDATA_int_regslice;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
reg   [0:0] out_stream_TKEEP_int_regslice;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
reg   [0:0] out_stream_TSTRB_int_regslice;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
reg   [0:0] out_stream_TLAST_int_regslice;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 grp_compute_depthwise_fu_288_ap_start_reg = 1'b0;
#0 grp_compute_pointwise_fu_316_ap_start_reg = 1'b0;
#0 grp_compute_standard_fu_340_ap_start_reg = 1'b0;
#0 grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_start_reg = 1'b0;
end

conv2d_blck_compute_depthwise grp_compute_depthwise_fu_288(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_compute_depthwise_fu_288_ap_start),
    .ap_done(grp_compute_depthwise_fu_288_ap_done),
    .ap_idle(grp_compute_depthwise_fu_288_ap_idle),
    .ap_ready(grp_compute_depthwise_fu_288_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(gmem0_0_AWREADY),
    .m_axi_gmem0_0_AWADDR(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_compute_depthwise_fu_288_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(gmem0_0_WREADY),
    .m_axi_gmem0_0_WDATA(grp_compute_depthwise_fu_288_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_compute_depthwise_fu_288_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_compute_depthwise_fu_288_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_compute_depthwise_fu_288_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_compute_depthwise_fu_288_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_compute_depthwise_fu_288_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(gmem0_0_BVALID),
    .m_axi_gmem0_0_BREADY(grp_compute_depthwise_fu_288_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .input_data(input_data_read_reg_649),
    .m_axi_gmem1_0_AWVALID(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(1'b0),
    .m_axi_gmem1_0_AWADDR(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_compute_depthwise_fu_288_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_compute_depthwise_fu_288_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(1'b0),
    .m_axi_gmem1_0_WDATA(grp_compute_depthwise_fu_288_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_compute_depthwise_fu_288_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_compute_depthwise_fu_288_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_compute_depthwise_fu_288_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_compute_depthwise_fu_288_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(gmem1_0_ARREADY),
    .m_axi_gmem1_0_ARADDR(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(gmem1_0_RVALID),
    .m_axi_gmem1_0_RREADY(grp_compute_depthwise_fu_288_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(gmem1_0_RDATA),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(gmem1_0_RFIFONUM),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(1'b0),
    .m_axi_gmem1_0_BREADY(grp_compute_depthwise_fu_288_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .filter_data(filter_data_read_reg_642),
    .bias_data(bias_data_read_reg_635),
    .multiplier_data(multiplier_data_read_reg_628),
    .shift_data(shift_data_read_reg_621),
    .output_data(output_data_read_reg_612),
    .input_h(h_in_read_reg_602),
    .input_w(w_in_read_reg_595),
    .input_ch(c_in_read_reg_588),
    .output_h(h_out_read_reg_572),
    .output_w(w_out_read_reg_564),
    .output_ch(c_out_read_reg_580),
    .kernel_h(kernel_h_reg_659),
    .stride_h(stride_read_reg_558),
    .pad_h(pad_w_reg_665),
    .input_offset(input_offset_read_reg_551),
    .weights_offset(weights_offset_read_reg_544),
    .output_offset(output_offset_read_reg_537),
    .act_min(act_min_read_reg_530),
    .act_max(act_max_read_reg_523),
    .grp_fu_385_p_din0(grp_compute_depthwise_fu_288_grp_fu_385_p_din0),
    .grp_fu_385_p_din1(grp_compute_depthwise_fu_288_grp_fu_385_p_din1),
    .grp_fu_385_p_dout0(grp_fu_385_p2),
    .grp_fu_385_p_ce(grp_compute_depthwise_fu_288_grp_fu_385_p_ce)
);

conv2d_blck_compute_pointwise grp_compute_pointwise_fu_316(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_compute_pointwise_fu_316_ap_start),
    .ap_done(grp_compute_pointwise_fu_316_ap_done),
    .ap_idle(grp_compute_pointwise_fu_316_ap_idle),
    .ap_ready(grp_compute_pointwise_fu_316_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(gmem0_0_AWREADY),
    .m_axi_gmem0_0_AWADDR(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_compute_pointwise_fu_316_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(gmem0_0_WREADY),
    .m_axi_gmem0_0_WDATA(grp_compute_pointwise_fu_316_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_compute_pointwise_fu_316_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_compute_pointwise_fu_316_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_compute_pointwise_fu_316_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_compute_pointwise_fu_316_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_compute_pointwise_fu_316_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(gmem0_0_BVALID),
    .m_axi_gmem0_0_BREADY(grp_compute_pointwise_fu_316_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .input_data(input_data_read_reg_649),
    .m_axi_gmem1_0_AWVALID(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(1'b0),
    .m_axi_gmem1_0_AWADDR(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_compute_pointwise_fu_316_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_compute_pointwise_fu_316_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(1'b0),
    .m_axi_gmem1_0_WDATA(grp_compute_pointwise_fu_316_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_compute_pointwise_fu_316_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_compute_pointwise_fu_316_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_compute_pointwise_fu_316_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_compute_pointwise_fu_316_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(gmem1_0_ARREADY),
    .m_axi_gmem1_0_ARADDR(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(gmem1_0_RVALID),
    .m_axi_gmem1_0_RREADY(grp_compute_pointwise_fu_316_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(gmem1_0_RDATA),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(gmem1_0_RFIFONUM),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(1'b0),
    .m_axi_gmem1_0_BREADY(grp_compute_pointwise_fu_316_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .filter_data(filter_data_read_reg_642),
    .bias_data(bias_data_read_reg_635),
    .multiplier_data(multiplier_data_read_reg_628),
    .shift_data(shift_data_read_reg_621),
    .output_data(output_data_read_reg_612),
    .input_w(w_in_read_reg_595),
    .input_ch(c_in_read_reg_588),
    .output_h(h_out_read_reg_572),
    .output_w(w_out_read_reg_564),
    .output_ch(c_out_read_reg_580),
    .input_offset(input_offset_read_reg_551),
    .weights_offset(weights_offset_read_reg_544),
    .output_offset(output_offset_read_reg_537),
    .act_min(act_min_read_reg_530),
    .act_max(act_max_read_reg_523)
);

conv2d_blck_compute_standard grp_compute_standard_fu_340(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_compute_standard_fu_340_ap_start),
    .ap_done(grp_compute_standard_fu_340_ap_done),
    .ap_idle(grp_compute_standard_fu_340_ap_idle),
    .ap_ready(grp_compute_standard_fu_340_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_compute_standard_fu_340_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(gmem0_0_AWREADY),
    .m_axi_gmem0_0_AWADDR(grp_compute_standard_fu_340_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_compute_standard_fu_340_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_compute_standard_fu_340_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_compute_standard_fu_340_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_compute_standard_fu_340_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_compute_standard_fu_340_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_compute_standard_fu_340_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_compute_standard_fu_340_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_compute_standard_fu_340_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_compute_standard_fu_340_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_compute_standard_fu_340_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_compute_standard_fu_340_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(gmem0_0_WREADY),
    .m_axi_gmem0_0_WDATA(grp_compute_standard_fu_340_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_compute_standard_fu_340_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_compute_standard_fu_340_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_compute_standard_fu_340_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_compute_standard_fu_340_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_compute_standard_fu_340_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_compute_standard_fu_340_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_compute_standard_fu_340_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_compute_standard_fu_340_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_compute_standard_fu_340_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_compute_standard_fu_340_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_compute_standard_fu_340_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_compute_standard_fu_340_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_compute_standard_fu_340_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_compute_standard_fu_340_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_compute_standard_fu_340_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_compute_standard_fu_340_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_compute_standard_fu_340_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(gmem0_0_BVALID),
    .m_axi_gmem0_0_BREADY(grp_compute_standard_fu_340_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .input_data(input_data_read_reg_649),
    .m_axi_gmem1_0_AWVALID(grp_compute_standard_fu_340_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(1'b0),
    .m_axi_gmem1_0_AWADDR(grp_compute_standard_fu_340_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_compute_standard_fu_340_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_compute_standard_fu_340_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_compute_standard_fu_340_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_compute_standard_fu_340_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_compute_standard_fu_340_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_compute_standard_fu_340_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_compute_standard_fu_340_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_compute_standard_fu_340_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_compute_standard_fu_340_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_compute_standard_fu_340_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_compute_standard_fu_340_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(1'b0),
    .m_axi_gmem1_0_WDATA(grp_compute_standard_fu_340_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_compute_standard_fu_340_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_compute_standard_fu_340_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_compute_standard_fu_340_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_compute_standard_fu_340_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_compute_standard_fu_340_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(gmem1_0_ARREADY),
    .m_axi_gmem1_0_ARADDR(grp_compute_standard_fu_340_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_compute_standard_fu_340_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_compute_standard_fu_340_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_compute_standard_fu_340_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_compute_standard_fu_340_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_compute_standard_fu_340_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_compute_standard_fu_340_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_compute_standard_fu_340_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_compute_standard_fu_340_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_compute_standard_fu_340_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_compute_standard_fu_340_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(gmem1_0_RVALID),
    .m_axi_gmem1_0_RREADY(grp_compute_standard_fu_340_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(gmem1_0_RDATA),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(gmem1_0_RFIFONUM),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(1'b0),
    .m_axi_gmem1_0_BREADY(grp_compute_standard_fu_340_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .filter_data(filter_data_read_reg_642),
    .bias_data(bias_data_read_reg_635),
    .multiplier_data(multiplier_data_read_reg_628),
    .shift_data(shift_data_read_reg_621),
    .output_data(output_data_read_reg_612),
    .input_h(h_in_read_reg_602),
    .input_w(w_in_read_reg_595),
    .input_ch(c_in_read_reg_588),
    .output_h(h_out_read_reg_572),
    .output_w(w_out_read_reg_564),
    .output_ch(c_out_read_reg_580),
    .kernel_h(kernel_h_reg_659),
    .stride_h(stride_read_reg_558),
    .pad_h(pad_w_reg_665),
    .input_offset(input_offset_read_reg_551),
    .weights_offset(weights_offset_read_reg_544),
    .output_offset(output_offset_read_reg_537),
    .act_min(act_min_read_reg_530),
    .act_max(act_max_read_reg_523)
);

conv2d_blck_conv2d_blck_Pipeline_STREAM_OUT grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_start),
    .ap_done(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_done),
    .ap_idle(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_idle),
    .ap_ready(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .out_stream_TREADY(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TREADY),
    .out_elems(out_elems_reg_676),
    .output_data(output_data_read_reg_612),
    .sub(sub_reg_703),
    .out_stream_TDATA(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TDATA),
    .out_stream_TVALID(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID),
    .out_stream_TKEEP(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TKEEP),
    .out_stream_TSTRB(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TSTRB),
    .out_stream_TLAST(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TLAST)
);

conv2d_blck_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_data(input_data),
    .filter_data(filter_data),
    .bias_data(bias_data),
    .multiplier_data(multiplier_data),
    .shift_data(shift_data),
    .output_data(output_data),
    .conv_type(conv_type),
    .h_in(h_in),
    .w_in(w_in),
    .c_in(c_in),
    .c_out(c_out),
    .h_out(h_out),
    .w_out(w_out),
    .stride(stride),
    .padding(padding),
    .input_offset(input_offset),
    .weights_offset(weights_offset),
    .output_offset(output_offset),
    .act_min(act_min),
    .act_max(act_max),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

conv2d_blck_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 8 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(gmem0_0_ARADDR),
    .I_CH0_ARLEN(gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(gmem0_0_AWVALID),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(gmem0_0_AWADDR),
    .I_CH0_AWLEN(gmem0_0_AWLEN),
    .I_CH0_WVALID(gmem0_0_WVALID),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(gmem0_0_WDATA),
    .I_CH0_WSTRB(gmem0_0_WSTRB),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(gmem0_0_BREADY)
);

conv2d_blck_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem1_0_ARVALID),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(gmem1_0_ARADDR),
    .I_CH0_ARLEN(gmem1_0_ARLEN),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(gmem1_0_RREADY),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

conv2d_blck_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U289(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_385_p0),
    .din1(grp_fu_385_p1),
    .ce(grp_fu_385_ce),
    .dout(grp_fu_385_p2)
);

conv2d_blck_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U290(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(c_out_read_reg_580),
    .din1(w_out_read_reg_564),
    .ce(grp_fu_389_ce),
    .dout(grp_fu_389_p2)
);

conv2d_blck_regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

conv2d_blck_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TKEEP_int_regslice),
    .vld_in(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

conv2d_blck_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TSTRB_int_regslice),
    .vld_in(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

conv2d_blck_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TLAST_int_regslice),
    .vld_in(grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_compute_depthwise_fu_288_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_compute_depthwise_fu_288_ap_start_reg <= 1'b1;
        end else if ((grp_compute_depthwise_fu_288_ap_ready == 1'b1)) begin
            grp_compute_depthwise_fu_288_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_compute_pointwise_fu_316_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_compute_pointwise_fu_316_ap_start_reg <= 1'b1;
        end else if ((grp_compute_pointwise_fu_316_ap_ready == 1'b1)) begin
            grp_compute_pointwise_fu_316_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_compute_standard_fu_340_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_compute_standard_fu_340_ap_start_reg <= 1'b1;
        end else if ((grp_compute_standard_fu_340_ap_ready == 1'b1)) begin
            grp_compute_standard_fu_340_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_ready == 1'b1)) begin
            grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        act_max_read_reg_523 <= act_max;
        act_min_read_reg_530 <= act_min;
        bias_data_read_reg_635 <= bias_data;
        c_in_read_reg_588 <= c_in;
        c_out_read_reg_580 <= c_out;
        conv_type_read_reg_608 <= conv_type;
        filter_data_read_reg_642 <= filter_data;
        h_in_read_reg_602 <= h_in;
        h_out_read_reg_572 <= h_out;
        input_data_read_reg_649 <= input_data;
        input_offset_read_reg_551 <= input_offset;
        kernel_h_reg_659[1] <= kernel_h_fu_465_p3[1];
        multiplier_data_read_reg_628 <= multiplier_data;
        output_data_read_reg_612 <= output_data;
        output_offset_read_reg_537 <= output_offset;
        pad_w_reg_665 <= pad_w_fu_485_p2;
        shift_data_read_reg_621 <= shift_data;
        stride_read_reg_558 <= stride;
        w_in_read_reg_595 <= w_in;
        w_out_read_reg_564 <= w_out;
        weights_offset_read_reg_544 <= weights_offset;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        empty_reg_688 <= empty_fu_500_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mul_ln367_reg_671 <= grp_fu_389_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        out_elems_reg_676 <= grp_fu_385_p2;
        trunc_ln369_reg_683 <= trunc_ln369_fu_491_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_stream_TDATA_reg <= grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TDATA;
        out_stream_TKEEP_reg <= grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TKEEP;
        out_stream_TLAST_reg <= grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TLAST;
        out_stream_TSTRB_reg <= grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        sub_reg_703 <= sub_fu_517_p2;
    end
end

always @ (*) begin
    if ((gmem0_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        gmem0_0_ARADDR = output_data_read_reg_612;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        gmem0_0_ARADDR = grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_ARADDR = grp_compute_standard_fu_340_m_axi_gmem0_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_ARADDR = grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_ARADDR = grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARADDR;
    end else begin
        gmem0_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        gmem0_0_ARLEN = zext_ln369_fu_513_p1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        gmem0_0_ARLEN = grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_ARLEN = grp_compute_standard_fu_340_m_axi_gmem0_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_ARLEN = grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_ARLEN = grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARLEN;
    end else begin
        gmem0_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        gmem0_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        gmem0_0_ARVALID = grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_ARVALID = grp_compute_standard_fu_340_m_axi_gmem0_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_ARVALID = grp_compute_pointwise_fu_316_m_axi_gmem0_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_ARVALID = grp_compute_depthwise_fu_288_m_axi_gmem0_0_ARVALID;
    end else begin
        gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_AWADDR = grp_compute_standard_fu_340_m_axi_gmem0_0_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_AWADDR = grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_AWADDR = grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWADDR;
    end else begin
        gmem0_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_AWLEN = grp_compute_standard_fu_340_m_axi_gmem0_0_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_AWLEN = grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_AWLEN = grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWLEN;
    end else begin
        gmem0_0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_AWVALID = grp_compute_standard_fu_340_m_axi_gmem0_0_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_AWVALID = grp_compute_pointwise_fu_316_m_axi_gmem0_0_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_AWVALID = grp_compute_depthwise_fu_288_m_axi_gmem0_0_AWVALID;
    end else begin
        gmem0_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_BREADY = grp_compute_standard_fu_340_m_axi_gmem0_0_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_BREADY = grp_compute_pointwise_fu_316_m_axi_gmem0_0_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_BREADY = grp_compute_depthwise_fu_288_m_axi_gmem0_0_BREADY;
    end else begin
        gmem0_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        gmem0_0_RREADY = grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_m_axi_gmem0_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_RREADY = grp_compute_standard_fu_340_m_axi_gmem0_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_RREADY = grp_compute_pointwise_fu_316_m_axi_gmem0_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_RREADY = grp_compute_depthwise_fu_288_m_axi_gmem0_0_RREADY;
    end else begin
        gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_WDATA = grp_compute_standard_fu_340_m_axi_gmem0_0_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_WDATA = grp_compute_pointwise_fu_316_m_axi_gmem0_0_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_WDATA = grp_compute_depthwise_fu_288_m_axi_gmem0_0_WDATA;
    end else begin
        gmem0_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_WSTRB = grp_compute_standard_fu_340_m_axi_gmem0_0_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_WSTRB = grp_compute_pointwise_fu_316_m_axi_gmem0_0_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_WSTRB = grp_compute_depthwise_fu_288_m_axi_gmem0_0_WSTRB;
    end else begin
        gmem0_0_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_WVALID = grp_compute_standard_fu_340_m_axi_gmem0_0_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_WVALID = grp_compute_pointwise_fu_316_m_axi_gmem0_0_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem0_0_WVALID = grp_compute_depthwise_fu_288_m_axi_gmem0_0_WVALID;
    end else begin
        gmem0_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_ARADDR = grp_compute_standard_fu_340_m_axi_gmem1_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_ARADDR = grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_ARADDR = grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARADDR;
    end else begin
        gmem1_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_ARLEN = grp_compute_standard_fu_340_m_axi_gmem1_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_ARLEN = grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_ARLEN = grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARLEN;
    end else begin
        gmem1_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_ARVALID = grp_compute_standard_fu_340_m_axi_gmem1_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_ARVALID = grp_compute_pointwise_fu_316_m_axi_gmem1_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_ARVALID = grp_compute_depthwise_fu_288_m_axi_gmem1_0_ARVALID;
    end else begin
        gmem1_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_RREADY = grp_compute_standard_fu_340_m_axi_gmem1_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((conv_type_read_reg_608 == 32'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_RREADY = grp_compute_pointwise_fu_316_m_axi_gmem1_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((conv_type_read_reg_608 == 32'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem1_0_RREADY = grp_compute_depthwise_fu_288_m_axi_gmem1_0_RREADY;
    end else begin
        gmem1_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_385_ce = grp_compute_depthwise_fu_288_grp_fu_385_p_ce;
    end else begin
        grp_fu_385_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_385_p0 = grp_compute_depthwise_fu_288_grp_fu_385_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_385_p0 = mul_ln367_reg_671;
    end else begin
        grp_fu_385_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_385_p1 = grp_compute_depthwise_fu_288_grp_fu_385_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_385_p1 = h_out_read_reg_572;
    end else begin
        grp_fu_385_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3)))) begin
        grp_fu_389_ce = 1'b1;
    end else begin
        grp_fu_389_ce = 1'b0;
    end
end

always @ (*) begin
    if (((grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_stream_TDATA_int_regslice = grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TDATA;
    end else begin
        out_stream_TDATA_int_regslice = out_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_stream_TKEEP_int_regslice = grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TKEEP;
    end else begin
        out_stream_TKEEP_int_regslice = out_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_stream_TLAST_int_regslice = grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TLAST;
    end else begin
        out_stream_TLAST_int_regslice = out_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_stream_TSTRB_int_regslice = grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TSTRB;
    end else begin
        out_stream_TSTRB_int_regslice = out_stream_TSTRB_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~(conv_type_read_read_fu_240_p2 == 32'd2) & ~(conv_type_read_read_fu_240_p2 == 32'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln307_4_fu_453_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((ap_start == 1'b1) & (conv_type_read_read_fu_240_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state1) & (or_ln307_4_fu_453_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((ap_start == 1'b1) & (conv_type_read_read_fu_240_p2 == 32'd1) & (1'b1 == ap_CS_fsm_state1) & (or_ln307_4_fu_453_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln307_4_fu_453_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state3_on_subcall_done = (((ap_predicate_op130_call_state3 == 1'b1) & (grp_compute_standard_fu_340_ap_done == 1'b0)) | ((grp_compute_pointwise_fu_316_ap_done == 1'b0) & (conv_type_read_reg_608 == 32'd2)) | ((grp_compute_depthwise_fu_288_ap_done == 1'b0) & (conv_type_read_reg_608 == 32'd1)));
end

always @ (*) begin
    ap_predicate_op130_call_state3 = (~(conv_type_read_reg_608 == 32'd2) & ~(conv_type_read_reg_608 == 32'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_type_read_read_fu_240_p2 = conv_type;

assign empty_fu_500_p3 = ((icmp_ln369_fu_495_p2[0:0] == 1'b1) ? trunc_ln369_reg_683 : 31'd0);

assign grp_compute_depthwise_fu_288_ap_start = grp_compute_depthwise_fu_288_ap_start_reg;

assign grp_compute_pointwise_fu_316_ap_start = grp_compute_pointwise_fu_316_ap_start_reg;

assign grp_compute_standard_fu_340_ap_start = grp_compute_standard_fu_340_ap_start_reg;

assign grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_start = grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_ap_start_reg;

assign grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state19);

assign icmp_ln307_fu_393_p2 = (($signed(h_in) > $signed(32'd64)) ? 1'b1 : 1'b0);

assign icmp_ln308_fu_399_p2 = (($signed(w_in) > $signed(32'd64)) ? 1'b1 : 1'b0);

assign icmp_ln309_fu_405_p2 = (($signed(c_in) > $signed(32'd64)) ? 1'b1 : 1'b0);

assign icmp_ln310_fu_411_p0 = c_out;

assign icmp_ln310_fu_411_p2 = (($signed(icmp_ln310_fu_411_p0) > $signed(32'd64)) ? 1'b1 : 1'b0);

assign icmp_ln311_fu_417_p0 = h_out;

assign icmp_ln311_fu_417_p2 = (($signed(icmp_ln311_fu_417_p0) > $signed(32'd64)) ? 1'b1 : 1'b0);

assign icmp_ln312_fu_423_p0 = w_out;

assign icmp_ln312_fu_423_p2 = (($signed(icmp_ln312_fu_423_p0) > $signed(32'd64)) ? 1'b1 : 1'b0);

assign icmp_ln321_fu_459_p2 = ((conv_type == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln326_fu_473_p2 = ((padding == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln369_fu_495_p2 = (($signed(out_elems_reg_676) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign kernel_h_fu_465_p3 = ((icmp_ln321_fu_459_p2[0:0] == 1'b1) ? 2'd1 : 2'd3);

assign or_ln307_1_fu_435_p2 = (or_ln307_fu_429_p2 | icmp_ln307_fu_393_p2);

assign or_ln307_2_fu_441_p2 = (icmp_ln312_fu_423_p2 | icmp_ln311_fu_417_p2);

assign or_ln307_3_fu_447_p2 = (or_ln307_2_fu_441_p2 | icmp_ln310_fu_411_p2);

assign or_ln307_4_fu_453_p2 = (or_ln307_3_fu_447_p2 | or_ln307_1_fu_435_p2);

assign or_ln307_fu_429_p2 = (icmp_ln309_fu_405_p2 | icmp_ln308_fu_399_p2);

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_conv2d_blck_Pipeline_STREAM_OUT_fu_368_out_stream_TVALID;

assign pad_h_1_fu_479_p2 = (icmp_ln321_fu_459_p2 ^ 1'd1);

assign pad_w_fu_485_p2 = (pad_h_1_fu_479_p2 & icmp_ln326_fu_473_p2);

assign sub_fu_517_p2 = ($signed(out_elems_reg_676) + $signed(32'd4294967295));

assign trunc_ln369_fu_491_p1 = grp_fu_385_p2[30:0];

assign zext_ln369_fu_513_p1 = empty_reg_688;

always @ (posedge ap_clk) begin
    kernel_h_reg_659[0] <= 1'b1;
end


reg find_kernel_block = 0;
// synthesis translate_off
`include "conv2d_blck_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //conv2d_blck

